### ISSUE TITLE
Token future time error

### ISSUE THREAD

**Issue by navee85** [kreait/firebase-tokens-php#13]
I am trying to verify the firebase token but sometimes, it is throwing token issued at future timestamp error, as in the following exception:

```
This token has been issued in the future at 2019-06-07T08:43:57+00:00, is your system time correct? {"exception":"[object] (Firebase\\Auth\\Token\\Exception\\IssuedInTheFuture(code: 0): This token has been issued in the future at 2019-06-07T08:43:57+00:00, is your system time correct? at /var/www/html/vendor/kreait/firebase-tokens/src/Verifier.php:95)
```

I debugged the the code, and I saw the following rows are the problem:

```
    private function verifyAuthTime(Token $token)
    {
       ...
        if ($token->getClaim('auth_time') > time()) {
            throw new InvalidToken($token, "The user's authentication time must be in the past");
        }
    }
```

The difference is between the auth_time and time() only a few seconds.

**Comment by jeromegamez** [comment]
Thanks for bringing this up! I've known the problem for quite some time now, and I think it's time that I address it. I'll work on this soon!

**Comment by jeromegamez** [comment]
Implemented #14 with 7e9877a0187e88c3d96372e2d06cdecc6db87254

**Comment by diego-lipinski-de-castro** [comment]
Hello, I have this problem now, could this be someting related to the server time?

**Comment by jeromegamez** [comment]
That's the likely cause, yes! You can verify a token with leeway to give the verification more "room": https://github.com/kreait/firebase-tokens-php#verify-an-id-token

**Comment by diego-lipinski-de-castro** [comment]
Yeah, I fixed it, server time was 20 minutes in the past, thanks for the return tho

**Comment by mahmoud7796** [comment]
i'm still getting wired error when test token in postman it works fine but when it is sent from client side angular it return this error: 

**The value 'eyJhbGciOiJSUzI...' is not a verified ID token:\n- - The token was issued in the future\n**

my code : 

```
 $auth = app('firebase.auth');
        try {
            return $auth->verifyIdToken($this->verifierId);
        } catch (FailedToVerifyToken $e) {
            throw new InvalidTokenException($e->getMessage(),$e->getCode());
        }
```

any solution plz
